---
title: "Data Manipulation"
output: github_document
---

This file is for doing data manipulation.

```{r}
library(tidyverse)
```

Load litters and pups.

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    na = c("", "NA", "."))

litters_df = janitor::clean_names(litters_df)

pups_df = 
  read_csv(
    "data/FAS_pups.csv",
    skip = 3,
    na = c("", "NA", "."))

pups_df = janitor::clean_names(pups_df)
```

```{r}
select(litters_df, group, litter_number)

select(litters_df, group:gd_of_birth)

select(litters_df, -group)

select(litters_df, starts_with("gd"))

select(litters_df, starts_with("gd"), group)

select(litters_df, GROUP = group, everything())

select(litters_df, -starts_with("gd"))
```

alternatives:

```{r}
rename(litters_df, GROUP = group)

relocate(litters_df, litter_number, gd0_weight)
```

for pups:

```{r}
select(pups_df, litter_number, sex, pd_ears)
```

## filter some rows

```{r}
filter(litters_df, gd_of_birth == 20)

filter(litters_df, pups_born_alive <=5)

filter(litters_df, group %in% c("Con7", "Con8"), pups_born_alive < 7)

filter(litters_df, pups_born_alive <4 | pups_born_alive > 8)

drop_na(litters_df, gd0_weight)

```

in pups, keep only rows where PD walk is less than 11 and sex is 2

```{r}
filter(pups_df, pd_walk < 11, sex == 2)
```

## mutate to change columns

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  wt_gain_squared = wt_gain ^ 2,
  group = str_to_lower(group))
```

for pups, make a variable that subtracts 7 from pd_walk

```{r}
mutate(pups_df, pd_walk_minus_7 = pd_walk -7)
```

```{r}
arrange(litters_df, pups_born_alive)
arrange(litters_df, desc(pups_born_alive))
```

Bad:

```{r}
litters_df = read_csv("data/FAS_litters,csv")
litters_rename_df = janitor::clean_names(litters_df)
litters_with_gd_df = select(litters_rename_df, group, starts_with("gd"))
```

instead:

```{r}
litters_df =
  read_csv("data/FAS_litters.csv", na = c("","NA",".")) |> 
  janitor::clean_names() |> 
  select(group, starts_with("gd")) |> 
  drop_na() |> 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  )
```

```{r}
pups_df =
  read_csv("data/FAS_pups.csv", na = c("","NA",".")) |> 
  janitor::clean_names() |> 
  select(litter_number, starts_with("pd")) |> 
  drop_na() |> 
  mutate(
    pd_walk_min_7 = pd_walk - 7)
```

                            
